base:
  path: /Users/wenxuanwang/Documents/工作/马哥公司/2ndRadar/test.txt
  readPath: /Users/wenxuanwang/Documents/工作/马哥公司/2ndRadar/test.xlsx
  directory: /templates/test.xlsx
  uploadDir: /Users/wenxuanwang/Documents
Server:
  port: 8081
logging:
  level:
    com.baomidou: debug
    com.baomidou.mybatisplus: debug
    com.baomidou.dynamic: debug
    com.vincent.gptspringbootmd.*: debug
    org.mybatis: debug
    org.springframework.jdbc.core: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'vincent2017727'
    url: jdbc:mysql://localhost:3306/gptDB?serverTimezone=UTC
    username: 'root'

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

springfox:
  documentation:
    enabled: true
    auto-startup: true
    swagger-ui:
      enabled: true
