base:
  path: /Users/wenxuanwang/Desktop/2ndRadar/test.txt
  directory: /templates/test.xlsx
Server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'vincent2017727'
    url: jdbc:mysql://localhost:3306/gptDB?serverTimezone=UTC
    username: 'root'

#### ???????swagger??issues????mvma
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


#swagger:
#  info:
#    title: Your API Title
#    description: Your API Description
#    version: 1.0.0
#  paths:
#    mapping: /api/**
#  host: localhost:8080
#  securitySchemes:
#    basicAuth:
#      type: http
#      scheme: basic

#  setting:            # ??Ui????????
#    language: en-US                   # Ui??????,???????:??(zh-CN)???(en-US)??????
#    enableSwaggerModels: true         # ???????SwaggerModel??????true
#    enableDocumentManage: true        # ???????"????"??????true
#    swaggerModelName: ?????       # ???SwaggerModel??
#    enableVersion: false              # ????????????????,??????????Ui????????
#    enableReloadCacheParameter: false # ?????Debug????????????,?????
#    enableAfterScript: true           # ??Tab????AfterScript??,????
#    enableFilterMultipartApiMethodType: POST    # ?????????????POST
#    enableFilterMultipartApis: false  # ??RequestMapping???????,????????????,?????,?????7??????????,???????,??????Post???????
#    enableRequestCache: true          # ??????????
#    enableHost: false                 # ????Host????false
#    enableHostText: 192.168.0.193:8000                # ????
#    enableHomeCustom: true            # ???????????????false
#    homeCustomLocation: classpath:markdown/home.md    # ????Markdown????
#    enableSearch: false             # ????Ui???????????false
#    enableFooter: false             # ????Footer????true
#    enableFooterCustom: true        # ???????Footer????false
#    footerCustomContent: Apache License 2.0           # ???Footer??
#    enableDynamicParameter: false   # ????????????????false
#    enableDebug: true               # ????????true
#    enableOpenApi: false            # ??OpenAPI??????true
#    enableGroup: true               # ??????????true